// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVJKyQPpnJkQWHY13plzEap2-KN3cOxQ',
    appId: '1:235497835527:web:658c5008a72c7994666ea2',
    messagingSenderId: '235497835527',
    projectId: 'bulvarsbor',
    authDomain: 'bulvarsbor.firebaseapp.com',
    storageBucket: 'bulvarsbor.firebasestorage.app',
    measurementId: 'G-344DPLFEFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eMT7zegG8hO6evAbsXCRzl5N4Da1wPU',
    appId: '1:235497835527:android:db464a9002e9db7a666ea2',
    messagingSenderId: '235497835527',
    projectId: 'bulvarsbor',
    storageBucket: 'bulvarsbor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBangQN1yIvYkepqNSoRcmu6_Ynyp4_4X4',
    appId: '1:235497835527:ios:a447c2383e1f5ab3666ea2',
    messagingSenderId: '235497835527',
    projectId: 'bulvarsbor',
    storageBucket: 'bulvarsbor.firebasestorage.app',
    iosBundleId: 'com.example.sborapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBangQN1yIvYkepqNSoRcmu6_Ynyp4_4X4',
    appId: '1:235497835527:ios:a447c2383e1f5ab3666ea2',
    messagingSenderId: '235497835527',
    projectId: 'bulvarsbor',
    storageBucket: 'bulvarsbor.firebasestorage.app',
    iosBundleId: 'com.example.sborapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVJKyQPpnJkQWHY13plzEap2-KN3cOxQ',
    appId: '1:235497835527:web:61a320131b36c24b666ea2',
    messagingSenderId: '235497835527',
    projectId: 'bulvarsbor',
    authDomain: 'bulvarsbor.firebaseapp.com',
    storageBucket: 'bulvarsbor.firebasestorage.app',
    measurementId: 'G-YV19B8YH0C',
  );
}
